apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-app/apps
    repoURL: https://github.com/peteqproj/manifests
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true