apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  destination:
    namespace: rabbitmq-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rabbitmq-operator
    repoURL: https://github.com/peteqproj/manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true