apiVersion: v1
kind: Service
metadata:
  name: peteq-command-service
spec:
  selector:
    app: peteq-command-service
  ports:
  - port: 80 
    name: web
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peteq-command-service
spec:
  selector:
    matchLabels:
      app: peteq-command-service
  template:
    metadata:
      labels:
        app: peteq-command-service
    spec:
      volumes: []
      containers:
      - name: peteq-command-service
        imagePullPolicy: Always
        args:
          - "start"
          - "command-service"
        image: peteqproj/peteq 
        env:
        - name: EVENTBUS_TYPE
          valueFrom:
            configMapKeyRef:
              key: eventbus_type
              name: configmap
        - name: COMMANDBUS_TYPE
          valueFrom:
            configMapKeyRef:
              key: commandbus_type 
              name: configmap
        - name: PORT
          value: "8080"
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              key: postgres_url
              name: configmap
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts: []
        ports:
        - containerPort: 8080
