apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: peteq-app
namePrefix: local-
commonLabels:
  env: local
resources:
- postgres-client.yaml
- postgres.yaml
- init-job.yaml
- rabbitmq-instance.yaml
- ../../base
configMapGenerator:
- name: configmap
  behavior: merge
  envs:
  - env
patches:
  - path: patch-mapping-api.yaml
    target:
      group: getambassador.io
      kind: Mapping
      version: v2
      name: peteq-api
  - path: patch-mapping-api.yaml
    target:
      group: getambassador.io
      kind: Mapping
      version: v2
      name: peteq-api-query
  - target:
      group: getambassador.io
      kind: Mapping
      version: v2
      name: peteq-api-command
    patch: |
      - op: replace
        path: "/spec/service"
        value: local-peteq-api
  - path: patch-mapping-ui.yaml
    target:
      group: getambassador.io
      kind: Mapping
      version: v2
      name: peteq-ui
patchesJson6902:
  - path: patch-rabbitmq-envs.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: peteq-command-service
  - path: patch-rabbitmq-envs.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: peteq-api