apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: peteq-app
namePrefix: local-
commonLabels:
  env: local
resources:
- postgres-client.yaml
- postgres.yaml
- init-job.yaml
- rabbitmq-instance.yaml
- ../../base
configMapGenerator:
- behavior: merge
  envs:
  - env
  name: configmap
images:
- name: peteqproj/peteq
  newName: peteqproj/peteq
  newTag: 0.5.0
patches:
- patch: |
    - op: replace
      path: "/spec/service"
      value: local-peteq-rest-api-service
  target:
    group: getambassador.io
    kind: Mapping
    name: peteq-rest-api
    version: v2
- patch: |
    - op: replace
      path: "/spec/service"
      value: local-peteq-query-service
  target:
    group: getambassador.io
    kind: Mapping
    name: peteq-api-query
    version: v2
- patch: |
    - op: replace
      path: "/spec/service"
      value: local-peteq-command-service
  target:
    group: getambassador.io
    kind: Mapping
    name: peteq-api-command
    version: v2
- path: patch-mapping-ui.yaml
  target:
    group: getambassador.io
    kind: Mapping
    name: peteq-ui
    version: v2
patchesJson6902:
- path: patch-rabbitmq-envs.yaml
  target:
    group: apps
    kind: Deployment
    name: peteq-command-service
    version: v1
- path: patch-rabbitmq-envs.yaml
  target:
    group: apps
    kind: Deployment
    name: peteq-query-service
    version: v1
- path: patch-rabbitmq-envs.yaml
  target:
    group: apps
    kind: Deployment
    name: peteq-rest-api-service
    version: v1
- path: patch-rabbitmq-envs.yaml
  target:
    group: apps
    kind: Deployment
    name: peteq-event-handler-service
    version: v1
